SysMon/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SysMon.PageViewModels;
using SysMon.Services;
using Microsoft.AspNetCore.Authorization;

namespace SysMon.Controllers
{
    [Authorize]
    public class ConfigController 
        : Controller
    {
        private readonly IConfigService configService;

        public ConfigController(
            IConfigService configService)
        {
            this.configService = configService;
        }

        public IActionResult Index()
        {
            var configs = configService.List();

            
            var SmtpServer = configs.Single(d => d.Key == "SMTP_SERVER");
            var SmtpPort = configs.Single(d => d.Key == "SMTP_PORT");
            var SmtpUserName = configs.Single(d => d.Key == "SMTP_USERNAME");
            var SmtpPassword = configs.Single(d => d.Key == "SMTP_PASSWORD");
            var Subject = configs.Single(d => d.Key == "SUBJECT");
            var AlertRepetion = configs.Single(d => d.Key == "ALERT_REPETITION");
            var AlertRepetitionRange = configs.Single(d => d.Key == "ALERT_REPETITION_RANGE");


            ConfigItem configItem = new ConfigItem();
            configItem.SmtpServer = SmtpServer.Value;
            configItem.SmtpUserName = SmtpUserName.Value;
            configItem.SmtpPort = SmtpPort.Value;
            configItem.Subject = Subject.Value;
            configItem.SmtpPassword = SmtpPassword.Value;
            configItem.AlertRepetition = int.Parse(AlertRepetion.Value);
            configItem.AlertRepetitionRange = int.Parse(AlertRepetitionRange.Value);

            return View(configItem);
        }

        [HttpPost]
        public IActionResult Index(ConfigItem configItem)
        {
            var configs = configService.List();

            var SmtpServer = configs.Single(d => d.Key == "SMTP_SERVER");
            if(SmtpServer.Value != configItem.SmtpServer)
            {
                SmtpServer.Value = configItem.SmtpServer;
                configService.Update(SmtpServer);
            }
            
            var SmtpPort = configs.Single(d => d.Key == "SMTP_PORT");
            if(SmtpPort.Value != configItem.SmtpPort)
            {
                SmtpPort.Value = configItem.SmtpPort;
                configService.Update(SmtpPort);
            }
               
            var SmtpUserName = configs.Single(d => d.Key == "SMTP_USERNAME");
            if(SmtpUserName.Value != configItem.SmtpUserName)
            {
                SmtpUserName.Value = configItem.SmtpUserName;
                configService.Update(SmtpUserName);
            }
            
            var SmtpPassword = configs.Single(d => d.Key == "SMTP_PASSWORD");
            if(!String.IsNullOrEmpty(configItem.SmtpPassword) && SmtpPassword.Value != configItem.SmtpPassword)
            {
                SmtpPassword.Value = configItem.SmtpPassword;
                configService.Update(SmtpPassword);
            }
            
            var Subject = configs.Single(d => d.Key == "SUBJECT");
            if(Subject.Value != configItem.Subject)
            {
                Subject.Value = configItem.Subject;
                configService.Update(Subject);
            }

            var AlertRepetition = configs.Single(d => d.Key == "ALERT_REPETITION");
            if (int.Parse(AlertRepetition.Value) != configItem.AlertRepetition)
            {
                AlertRepetition.Value = configItem.AlertRepetition.ToString();
                configService.Update(AlertRepetition);
            }

            var AlertRepetitionRange = configs.Single(d => d.Key == "ALERT_REPETITION_RANGE");
            if (int.Parse(AlertRepetitionRange.Value) != configItem.AlertRepetitionRange)
            {
                AlertRepetitionRange.Value = configItem.Subject;
                configService.Update(AlertRepetitionRange);
            }

            return View();
        }
    }
}

SysMon/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SysMon.Models;
using SysMon.PageViewModels;
using SysMon.Services;
using Microsoft.AspNetCore.Authorization;

namespace SysMon.Controllers
{
    [Authorize]
    public class GroupController 
        : Controller
    {
        private readonly IGroupService groupService;
        public GroupController(
            IGroupService groupService)
        {
            this.groupService = groupService;
        }

        public IActionResult Index()
        {
            var groups = groupService.List();

            List<GroupItem> groupItems = new List<GroupItem>();
            foreach (var group in groups)
            {
                GroupItem groupItem = new GroupItem();
                groupItem.GroupName = group.GroupName;
                groupItem.Explanation = group.Explanation;
                groupItem.Id = group.Id;
                groupItems.Add(groupItem);
            }

            return View(groupItems);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(GroupItem groupItem)
        {
            try
            {
                var group = new Group();
                group.GroupName = groupItem.GroupName;
                group.Explanation = groupItem.Explanation;
                groupService.Add(group);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Error while group create");
                return View(groupItem);
            }
        }

        public IActionResult Edit(int id)
        {
            var group = groupService.Get(id);
            var groupItem = new GroupItem();
            groupItem.GroupName = group.GroupName;
            groupItem.Explanation = group.Explanation;
            return View(groupItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, GroupItem groupItem)
        {
            try
            {
                var group = groupService.Get(id);
                group.GroupName = groupItem.GroupName;
                group.Explanation = groupItem.Explanation;
                groupService.Update(group);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Error while group update");
                return View(groupItem);
            }
        }

        public IActionResult Remove(int id) 
        {
            try
            {
                groupService.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Error while group delete");
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

SysMon/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SysMon.Models;
using SysMon.PageViewModels;
using SysMon.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace SysMon.Controllers
{
    [Authorize]
    public class JobController 
        : Controller
    {
        private readonly IUserService userService;
        private readonly IJobService jobService;
        private readonly IJobConfigService jobConfigService;
        private readonly UserManager<User> userManager;

        public JobController(
            IUserService userService,
            IJobService jobService,
            IJobConfigService jobConfigService,
            UserManager<User> userManager)
        {
            this.userService = userService;
            this.jobService = jobService;
            this.jobConfigService = jobConfigService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var currentUser = userService.GetUser();
            //var currentUser = userService.GetUserById("1");

            var userJobConfigs = new List<JobConfig>();
            if (currentUser != null)
            {
                var userId = currentUser.Id;
                userJobConfigs = jobConfigService.List(d => d.UserId == userId).ToList();
            }

            var jobs = jobService.List();

            List<JobItem> jobItems = new List<JobItem>();
            foreach (var job in jobs)
            {
                JobItem jobItem = new JobItem();
                jobItem.Delay = job.Delay;
                jobItem.EndTime = job.EndTime;
                jobItem.Id = job.Id;
                jobItem.JobDetail = job.JobDetail;
                jobItem.JobName = job.JobName;
                jobItem.JobRunId = job.JobRunId;
                jobItem.JobState = job.JobState.ToString();
                jobItem.ProjectName = job.ProjectName;
                jobItem.StartTime = job.StartTime;

                if(userJobConfigs.Count > 0)
                {
                    var userJobConfig = userJobConfigs.SingleOrDefault(d => d.JobId == job.Id);
                    jobItem.IsOwned = userJobConfig != null ? true : false;
                }
                else
                {
                    jobItem.IsOwned = false;
                }

                jobItems.Add(jobItem);
            }
            return View(jobItems);
        }

        public IActionResult MyJob()
        {
            // kullanıcıya tanımlı jobConfig Listesi
            var currentUser = userService.GetUser();
            //var currentUser = userService.GetUserById("1");
            if (currentUser != null)
            {
                var userId = currentUser.Id;
                var userJobConfigs = jobConfigService.List(d => d.UserId == userId);

                if(User.IsInRole("Manager"))
                {
                    
                }

                List<MyJobItem> jobItems = new List<MyJobItem>();
                foreach (var userJobConfig in userJobConfigs)
                {
                    var jobId = userJobConfig.JobId;
                    var job = jobService.Get(jobId);

                    MyJobItem jobItem = new MyJobItem();
                    jobItem.Delay = job.Delay;
                    jobItem.EndTime = job.EndTime;
                    jobItem.Id = job.Id;
                    jobItem.JobDetail = job.JobDetail;
                    jobItem.JobName = job.JobName;
                    jobItem.JobRunId = job.JobRunId;
                    jobItem.JobState = job.JobState.ToString();
                    jobItem.ProjectName = job.ProjectName;
                    jobItem.StartTime = job.StartTime;
                    // config detils
                    jobItem.JobConfigId = userJobConfig.Id;
                    jobItem.NotifyOnDelay = userJobConfig.NotifyOnDelay;
                    jobItem.NotifyOnFailure = userJobConfig.NotifyOnFailure;
                    jobItem.Hot = userJobConfig.Hot;
                    jobItem.ThresholdForDelay = userJobConfig.ThresholdForDelay;
                    jobItems.Add(jobItem);
                }
                return View(jobItems);
            }

            return View(new List<MyJobItem>());
        }

        public IActionResult MyGroupJob()
        {
            // kullanıcıya tanımlı jobConfig Listesi
            var currentUser = userService.GetUser();
            //var currentUser = userService.GetUserById("1");
            if (currentUser != null)
            {
                var userId = currentUser.Id;
                var groupId = currentUser.GroupId;

                var users = userManager.Users.Where(d => d.GroupId == groupId && d.Id != userId);


                List<MyJobItem> jobItems = new List<MyJobItem>();

                foreach (var user in users)
                {
                    var userJobConfigs = jobConfigService.List(d => d.UserId == user.Id);

                    foreach (var userJobConfig in userJobConfigs)
                    {
                        var jobId = userJobConfig.JobId;
                        var job = jobService.Get(jobId);

                        MyJobItem jobItem = new MyJobItem();
                        jobItem.UserName = user.UserName;
                        jobItem.Delay = job.Delay;
                        jobItem.EndTime = job.EndTime;
                        jobItem.Id = job.Id;
                        jobItem.JobDetail = job.JobDetail;
                        jobItem.JobName = job.JobName;
                        jobItem.JobRunId = job.JobRunId;
                        jobItem.JobState = job.JobState.ToString();
                        jobItem.ProjectName = job.ProjectName;
                        jobItem.StartTime = job.StartTime;
                        // config detils
                        jobItem.JobConfigId = userJobConfig.Id;
                        jobItem.NotifyOnDelay = userJobConfig.NotifyOnDelay;
                        jobItem.NotifyOnFailure = userJobConfig.NotifyOnFailure;
                        jobItem.Hot = userJobConfig.Hot;
                        jobItem.ThresholdForDelay = userJobConfig.ThresholdForDelay;
                        jobItems.Add(jobItem);
                    }
                }
                return View(jobItems);
            }

            return View(new List<MyJobItem>());
        }

        public IActionResult Add(int id)
        {
            var currentUser = userService.GetUser();
            //var currentUser = userService.GetUserById("1");
            if (currentUser != null)
            {
                var jobId = id;
                var userId = currentUser.Id;

                JobConfig jobConfig = new JobConfig();
                jobConfig.UserId = userId;
                jobConfig.JobId = jobId;
                jobConfigService.Add(jobConfig);
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int id)
        {
            var currentUser = userService.GetUser();
            //var currentUser = userService.GetUserById("1");
            if (currentUser != null)
            {
                var jobId = id;
                var userId = currentUser.Id;

                var userJobConfigs = jobConfigService.List(d => d.UserId == userId);
                var userJobConfig = userJobConfigs.SingleOrDefault(d => d.JobId == jobId);
                if(userJobConfig != null)
                {
                    jobConfigService.Remove(userJobConfig.Id);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Config(int id)
        {
            // kullanıcıya tanımlı jobConfig Listesi
            var currentUser = userService.GetUser();
            //var currentUser = userService.GetUserById("1");
            if (currentUser != null)
            {
                var userId = currentUser.Id;
                var userJobConfig = jobConfigService.Get(id);
                var job = jobService.Get(userJobConfig.JobId);

                if (userJobConfig != null)
                {
                    var userJobConfigItem = new JobConfigItem();
                    userJobConfigItem.Id = userJobConfig.Id;
                    userJobConfigItem.Hot = userJobConfig.Hot;
                    userJobConfigItem.NotifyOnDelay = userJobConfig.NotifyOnDelay;
                    userJobConfigItem.NotifyOnFailure = userJobConfig.NotifyOnFailure;
                    userJobConfigItem.ThresholdForDelay = userJobConfig.ThresholdForDelay;
                    userJobConfigItem.JobName = job.JobName;
                    userJobConfigItem.JobDetail = job.JobDetail;

                    return View(userJobConfigItem);
                }
                return RedirectToAction(nameof(MyJob));
            }
            return RedirectToAction(nameof(MyJob));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Config(int id, JobConfigItem jobConfigItem)
        {
            try
            {
                var userJobConfig = jobConfigService.Get(id);
                userJobConfig.Hot = jobConfigItem.Hot;
                userJobConfig.NotifyOnDelay = jobConfigItem.NotifyOnDelay;
                userJobConfig.NotifyOnFailure = jobConfigItem.NotifyOnFailure;
                userJobConfig.ThresholdForDelay = jobConfigItem.ThresholdForDelay;

                jobConfigService.Update(userJobConfig);

                return RedirectToAction(nameof(MyJob));
            }
            catch
            {
                return View();
            }
        }
    }
}

SysMon/Views/Shared/_AuthHeader.cshtml
<!-- HEADER -->
<header id="header">
    <div id="logo-group">
        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo">
            <a href="/">
                <img src="~/img/logo.png" alt="SmartAdmin">
            </a>
        </span>
        <!-- END LOGO PLACEHOLDER -->
    </div>

    <span id="extr-page-header-space">
        <span hide-if-active asp-controller="Account" asp-action="Login">
            <span class="hidden-mobile hidden-xs">Already registered?</span> <a asp-controller="Account" asp-action="Login" class="btn btn-danger">Sign in</a>
        </span>
        <span show-if-active asp-controller="Account" asp-action="Login">
            <span class="hidden-mobile hidden-xs">Need an account?</span> <a asp-controller="Account" asp-action="Register" class="btn btn-danger">Create account</a>
        </span>
    </span>
</header>
<!-- END HEADER -->

SysMon/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en-us" id="extr-page">
<head>
    <meta charset="utf-8" />

    <title>SmartAdmin for ASP.NET Core 2.0</title>
    <meta name="description" content="SmartAdmin for ASP.NET Core 2.0" />
    <meta name="author" content="SmartAdmin" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Basic Styles -->
    @{ await Html.RenderPartialAsync("_StylesheetsPartial"); }

    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/img/favicon/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="~/img/favicon/favicon.ico" type="image/x-icon" />

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700" />

    <!-- Specifying a Webpage Icon for Web Clip Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/img/splash/sptouch-icon-iphone.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/img/splash/touch-icon-ipad.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="~/img/splash/touch-icon-iphone-retina.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="~/img/splash/touch-icon-ipad-retina.png" />

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)" />
    <link rel="apple-touch-startup-image" href="~/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)" />
    <link rel="apple-touch-startup-image" href="~/img/splash/iphone.png" media="screen and (max-device-width: 320px)" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
</head>
<body class="animated fadeInDown">
    @{ await Html.RenderPartialAsync("_AuthHeader"); }
    <!-- MAIN PANEL -->
    <div id="main" role="main">
        <!-- MAIN CONTENT -->
        <div id="content" class="container">
            @RenderBody()
        </div>
        <!-- END MAIN CONTENT -->
    </div>
    <!-- END MAIN PANEL -->
    @{ await Html.RenderPartialAsync("_Scripts"); }
    @RenderSection("Scripts", required: false)
</body>
</html>

SysMon/Views/Shared/_Footer.cshtml
<!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">SysMon <span class="hidden-xs"> - Job Monitoring System</span> © 2019</span>
        </div>

        <div class="col-xs-6 col-sm-6 text-right hidden-xs">
            <div class="txt-color-white inline-block">
                <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i>
                @*<div class="btn-group dropup">
                    <button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
                        <i class="fa fa-link"></i> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right text-left">
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Server Load</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">
                                    Memory Load <span class="text-danger">*critical*</span>
                                </p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <button class="btn btn-block btn-default">refresh</button>
                            </div>
                        </li>
                    </ul>
                </div>*@
            </div>
        </div>
    </div>
</div>
<!-- END PAGE FOOTER -->

SysMon/Views/Shared/_Navigation.cshtml
@inject UserManager<User> UserManager

@{
    var currentUser = @UserManager.GetUserAsync(User);
    var userRoles = @UserManager.GetRolesAsync(currentUser.Result);
    var roleName = userRoles.Result.FirstOrDefault();
};

<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<aside id="left-panel">
    <!-- User info -->
    <div class="login-info">
        <span>
            <!-- User image size is adjusted inside CSS, it should stay as it -->
            <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
                <img src="~/img/avatars/sunny.png" alt="me" class="online" />
                <span>
                    @User.Identity.Name
                </span>
                <i class="fa fa-angle-down"></i>
            </a>
        </span>
    </div>
   
    <!-- end user info -->
    <!-- NAVIGATION : This navigation is also responsive-->
    <nav>
        <!--
        NOTE: Notice the gaps after each icon usage <i></i>..
        Please note that these links work a bit different than
        traditional href="" links. See documentation for details.
        -->

        <ul>
            <li>
                <a href="#">
                    <i class="fa fa-lg fa-fw fa-windows"></i> <span class="menu-item-parent"> My Account</span>
                </a>
                <ul>
                    <li is-active-route asp-controller="Manage" asp-action="Index">
                        <a asp-controller="Manage" asp-action="Index" title="Empty">
                            <span class="menu-item-parent">My Profile</span>
                        </a>
                    </li>
                    <li is-active-route asp-controller="Manage" asp-action="ChangePassword">
                        <a asp-controller="Manage" asp-action="ChangePassword" title="Empty">
                            <span class="menu-item-parent">Change Password</span>
                        </a>
                    </li>
                    <li is-active-route asp-controller="Account" asp-action="LogOff">
                        <a asp-controller="Account" asp-action="LogOff" title="Empty">
                            <span class="menu-item-parent">Log Off</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li is-active-route asp-controller="Home">
                <a href="#" title="Dashboard">
                    <i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span>
                </a>
                <ul>
                    @if (User.IsInRole("SysmonUser"))
                    {
                        <li is-active-route asp-controller="Job" asp-action="Index">
                            <a asp-controller="Job" asp-action="Index" title="Empty">
                                <span class="menu-item-parent">Config Job</span>
                            </a>
                        </li>
                        <li is-active-route asp-controller="Job" asp-action="MyJob">
                            <a asp-controller="Job" asp-action="MyJob" title="Empty">
                                <span class="menu-item-parent">My Job</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("Manager"))
                    {
                        <li is-active-route asp-controller="Job" asp-action="Index">
                            <a asp-controller="Job" asp-action="Index" title="Empty">
                                <span class="menu-item-parent">Config Job</span>
                            </a>
                        </li>
                        <li is-active-route asp-controller="Job" asp-action="MyJob">
                            <a asp-controller="Job" asp-action="MyJob" title="Empty">
                                <span class="menu-item-parent">My Job</span>
                            </a>
                        </li>
                        <li is-active-route asp-controller="Job" asp-action="MyGroupJob">
                            <a asp-controller="Job" asp-action="MyGroupJob" title="Empty">
                                <span class="menu-item-parent">My Group Job</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("SystemAdmin"))
                    {
                        <li is-active-route asp-controller="Group" asp-action="Index">
                            <a asp-controller="Group" asp-action="Index" title="Empty">
                                <span class="menu-item-parent">Groups</span>
                            </a>
                        </li>
                        <li is-active-route asp-controller="Watcher" asp-action="Index">
                            <a asp-controller="Watcher" asp-action="Index" title="Empty">
                                <span class="menu-item-parent">Watchers</span>
                            </a>
                        </li>
                        <li is-active-route asp-controller="User" asp-action="Index">
                            <a asp-controller="User" asp-action="Index" title="Empty">
                                <span class="menu-item-parent">Users</span>
                            </a>
                        </li>
                    }
                </ul>
            </li>
            @if (User.IsInRole("SystemAdmin"))
            {
                <li>
                    <a href="#">
                        <i class="fa fa-lg fa-fw fa-windows"></i> <span class="menu-item-parent"> System </span>
                    </a>
                    <ul>
                        <li is-active-route asp-controller="Config" asp-action="Index">
                            <a asp-controller="Config" asp-action="Index" title="Empty">
                                <span class="menu-item-parent">Configuration</span>
                            </a>
                        </li>
                    </ul>
                </li>
            }
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>
</aside>
<!-- END NAVIGATION -->

SysMon/Views/Shared/_Ribbon.cshtml
<!-- RIBBON -->
<div id="ribbon">

    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
            <i class="fa fa-refresh"></i>
        </span>
    </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li>Home</li>
        <li>Dashboard</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
        <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
        <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
        <span id="search" class="btn btn-ribbon" data-title="search">
            <i class="fa-search"></i> <span class="hidden-mobile">Search</span>
        </span>
    </span> -->

</div>
<!-- END RIBBON -->